-- MySQL Script generated by MySQL Workbench
-- Mon Oct 15 16:56:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema community
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `community` ;

-- -----------------------------------------------------
-- Schema community
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `community` DEFAULT CHARACTER SET utf8 ;
USE `community` ;

-- -----------------------------------------------------
-- Table `community`.`communities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `community`.`communities` ;

CREATE TABLE IF NOT EXISTS `community`.`communities` (
  `uuid` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `name` VARCHAR(100) NOT NULL,
  `tagline` VARCHAR(100) NOT NULL,
  `desc` TEXT NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  `social_links` JSON NULL,
  `avatar_upload_uuid` CHAR(36) NULL,
  `tier` JSON NOT NULL,
  `visibility` ENUM('public', 'private', 'secret') NOT NULL DEFAULT 'public',
  `is_active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `community`.`community_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `community`.`community_users` ;

CREATE TABLE IF NOT EXISTS `community`.`community_users` (
  `community_uuid` CHAR(36) NOT NULL,
  `user_uuid` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `status` ENUM('invited', 'applied', 'approved', 'removed', 'banned') NOT NULL,
  `role` ENUM('guest', 'member', 'moderator', 'admin') NOT NULL,
  PRIMARY KEY (`community_uuid`, `user_uuid`));


-- -----------------------------------------------------
-- Table `community`.`conversation_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `community`.`conversation_categories` ;

CREATE TABLE IF NOT EXISTS `community`.`conversation_categories` (
  `uuid` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `community_uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `visibility` ENUM('public', 'private', 'secret') NOT NULL DEFAULT 'public',
  `min_role_required` ENUM('guest', 'member', 'moderator', 'admin') NOT NULL,
  PRIMARY KEY (`uuid`));


-- -----------------------------------------------------
-- Table `community`.`conversation_posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `community`.`conversation_posts` ;

CREATE TABLE IF NOT EXISTS `community`.`conversation_posts` (
  `uuid` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `parent_uuid` CHAR(36) NULL,
  `community_uuid` CHAR(36) NOT NULL,
  `category_uuid` CHAR(36) NULL,
  `content` LONGTEXT NOT NULL,
  `view_count` INT NULL DEFAULT 0,
  `attachment_upload_uuids` JSON NULL,
  PRIMARY KEY (`uuid`));


-- -----------------------------------------------------
-- Table `community`.`uploads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `community`.`uploads` ;

CREATE TABLE IF NOT EXISTS `community`.`uploads` (
  `uuid` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `owner_uuid` CHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `original_file_name` VARCHAR(100) NOT NULL,
  `type` ENUM('user_avatar', 'community_avatar', 'post_attachment') NOT NULL,
  `short_desc` VARCHAR(250) NULL,
  PRIMARY KEY (`uuid`));


-- -----------------------------------------------------
-- Table `community`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `community`.`users` ;

CREATE TABLE IF NOT EXISTS `community`.`users` (
  `uuid` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(25) NULL,
  `last_name` VARCHAR(25) NULL,
  `attributes` JSON NULL,
  `location` VARCHAR(25) NULL,
  `avatar_upload_uuid` CHAR(36) NULL,
  `last_seen_at` TIMESTAMP NULL,
  `confirmed_email_at` TIMESTAMP NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
